### ISSUE TITLE
A error occured

### ISSUE THREAD

**Issue by Andy6M** [hspark1212/MOFTransformer#98]
it were caused when using docker image nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04 and all default. weird.

`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
Missing logger folder: ./logs/pretrained_mof_seed0_from_pretrained_model
read /usr/local/lib/python3.8/dist-packages/moftransformer/examples/dataset/train_example.json...
read /usr/local/lib/python3.8/dist-packages/moftransformer/examples/dataset/val_example.json...
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loading `train_dataloader` to estimate number of stepping batches.
/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py:1891: PossibleUserWarning: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=10). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
max_epochs: 10 | max_steps: 20 | warmup_steps : 1 | weight_decay : 0.01 | decay_power : 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/moftransformer/run.py", line 205, in run
    main(config)
  File "/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/moftransformer/run.py", line 276, in main
    trainer.fit(model, datamodule=dm)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 700, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/single_device.py", line 74, in setup
    super().setup(trainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 153, in setup
    self.setup_optimizers(trainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 141, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/optimizer.py", line 194, in _init_optimizers_and_lr_schedulers
    _validate_scheduler_api(lr_scheduler_configs, model)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/optimizer.py", line 351, in _validate_scheduler_api
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `LambdaLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

**Comment by Andy6M** [comment]
it seems could skip by manually set torch's version as 1.9.0 and torchvision's as 0.10.0 and downgrade mp-api
please consider re-write the call logic of lighting api or limit the version of torch.
(btw ubuntu 22.04 is using python3.10 as default thus uncompatiable with torch1.9.0)

**Comment by Andy6M** [comment]
and problem #2. seems you build your makefile inside the gridy. i could only clean ( by changing command as uninstall) it and build again... sad.

**Comment by hspark1212** [comment]
Thank you for your suggestion. We are currently working on version 2.0.0 and will take your feedback into account.
